### ISSUE TITLE
自动更新重启后，qqbot会离线。频道内私聊机器人提示“该机器人去火星了，稍后再试吧”

### ISSUE THREAD

**Issue by QYCDev** [TimeRainStarSky/Yunzai-QQBot-Plugin#11]
RT
需要重新用【#QQBot设置】绑定qqbot才能启用

**Comment by TimeRainStarSky** [comment]
日志呢

**Comment by AUndead** [comment]
作者我重启后有时也有这个问题:
1.日志如下:
[TRSSYz][22:04:04.611][MARK] [stdin] 标准输入(stdin) 已连接
[TRSSYz][22:04:09.616][INFO] 加载适配器[6个]
[TRSSYz][22:04:09.616][INFO] [WebSocket] 连接地址：ws://localhost:2536/[GSUIDCore,ComWeChat,OPQBot,OneBotv11,go-cqhttp]
[TRSSYz][22:04:09.617][MARK] ----^_^----
[TRSSYz][22:04:15.088][ERRO] [unhandledRejection] AxiosError: getaddrinfo EAI_AGAIN bots.qq.com
    at AxiosError.from (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:836:14)
    at RedirectableRequest.handleRequestError (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3086:25)
    at RedirectableRequest.emit (node:events:517:28)
    at eventHandlers.<computed> (/genshin/qbot/Yunzai/node_modules/.pnpm/follow-redirects@1.15.6_debug@4.3.4/node_modules/follow-redirects/index.js:38:24)
    at ClientRequest.emit (node:events:517:28)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
    at Axios.request (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3876:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
                                                                                                                                                                                hostname: 'bots.qq.com',
                                                                                                                                                                                syscall: 'getaddrinfo',
                                                                                                                                                                                code: 'EAI_AGAIN',
                                                                                                                                                                                errno: -3001,
                                                                                                                                                                                message: 'getaddrinfo EAI_AGAIN bots.qq.com',
                                                                                                                                                                                [stack]: 'Error: getaddrinfo EAI_AGAIN bots.qq.com\n' +
    '    at AxiosError.from (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:836:14)\n' +
    '    at RedirectableRequest.handleRequestError (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3086:25)\n' +
    '    at RedirectableRequest.emit (node:events:517:28)\n' +
    '    at eventHandlers.<computed> (/genshin/qbot/Yunzai/node_modules/.pnpm/follow-redirects@1.15.6_debug@4.3.4/node_modules/follow-redirects/index.js:38:24)\n' +
    '    at ClientRequest.emit (node:events:517:28)\n' +
    '    at TLSSocket.socketErrorListener (node:_http_client:501:9)\n' +
    '    at TLSSocket.emit (node:events:517:28)\n' +
    '    at emitErrorNT (node:internal/streams/destroy:151:8)\n' +
    '    at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n' +
    '    at Axios.request (/genshin/qbot/Yunzai/node_modules/.pnpm/axios@1.6.8/node_modules/axios/dist/node/axios.cjs:3876:41)\n' +
    '    '... 77 more characters,
                                                                                                                                                                                name: 'Error',
                                                                                                                                                                                config: {
                                                                      transitional: { silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false },
                                                                      adapter: [ 'xhr', 'http', [length]: 2 ],
                                                                      transformRequest: [
      <ref *1> [Function: transformRequest] {
        [length]: 2,
        [name]: 'transformRequest',
        [prototype]: { [constructor]: [Circular *1] }
      },
      [length]: 1
    ],
                                                                      transformResponse: [
      <ref *2> [Function: transformResponse] {
        [length]: 1,
        [name]: 'transformResponse',
        [prototype]: { [constructor]: [Circular *2] }
      },
      [length]: 1
    ],
                                                                      timeout: 0,
                                                                      xsrfCookieName: 'XSRF-TOKEN',
                                                                      xsrfHeaderName: 'X-XSRF-TOKEN',
                                                                      maxContentLength: -1,
                                                                      maxBodyLength: -1,
                                                                      env: {
                  FormData: <ref *3> [Function: FormData] {
                    [length]: 1,
                    [name]: 'FormData',
                    [arguments]: null,
                    [caller]: null,
                    [prototype]: CombinedStream {
          [constructor]: [Circular *3],
          append: <ref *4> [Function (anonymous)] {
            [length]: 3,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *4] }
          },
          _trackLength: <ref *5> [Function (anonymous)] {
            [length]: 3,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *5] }
          },
          _lengthRetriever: <ref *6> [Function (anonymous)] {
            [length]: 2,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *6] }
          },
          _multiPartHeader: <ref *7> [Function (anonymous)] {
            [length]: 3,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *7] }
          },
          _getContentDisposition: <ref *8> [Function (anonymous)] {
            [length]: 2,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *8] }
          },
          _getContentType: <ref *9> [Function (anonymous)] {
            [length]: 2,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *9] }
          },
          _multiPartFooter: <ref *10> [Function (anonymous)] {
            [length]: 0,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *10] }
          },
          _lastBoundary: <ref *11> [Function (anonymous)] {
            [length]: 0,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *11] }
          },
          getHeaders: <ref *12> [Function (anonymous)] {
            [length]: 1,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *12] }
          },
          setBoundary: <ref *13> [Function (anonymous)] {
            [length]: 1,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *13] }
          },
          getBoundary: <ref *14> [Function (anonymous)] {
            [length]: 0,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *14] }
          },
          getBuffer: <ref *15> [Function (anonymous)] {
            [length]: 0,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor]: [Circular *15] }
          },
          _generateBoundary: <ref *16> [Function (anonymous)] {
            [length]: 0,
            [name]: '',
            [arguments]: null,
            [caller]: null,
            [prototype]: { [constructor...
(node:1206145) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)

重启几次后又恢复但是过一会又私掉了...
