### ISSUE TITLE
QQBot插件无法发送图片

### ISSUE THREAD

**Issue by lifnegqaq** [TimeRainStarSky/Yunzai-QQBot-Plugin#14]
[10:20:28.673][ERRO][TRSSYz] [图片生成][miao-plugin/help/index] 图片生成失败 Error: Requesting main frame too early!                                               at assert (file:///root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/util/assert.js:15:15)                                                        at FrameManager.mainFrame (file:///root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/puppeteer-core@23.0.2/node_modules/puppeteer-core/lib/esm/puppeteer/cdp/FrameManager.js:201:9)                                   at CdpPage.mainFrame (file:///root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/puppeteer-core@23.0.2/no
de_modules/puppeteer-core/lib/esm/puppeteer/cdp/Page.js:383:35)              95
    at CdpPage.goto (file:///root/TRSS_AllBot/TRSS-Yunzai/node_modules/.pnpm/puppeteer-core@23.0.2/node_mo
 ❐ TRSS  3  7:18:10  24-08-11  10562  localhost 3:31)                                                    at Puppeteer.screenshot [as render] (file:///root/TRSS_AllBot/TRSS-Yunzai/renderers/puppeteer/lib/puppeteer.js:191:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                             at async renderer.screenshot (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/puppeteer/puppeteer.js:10:15)
    at async Runtime.render (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/plugins/runtime.js:221:18)              at async cls.render (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/miao-plugin/apps/help/Help.js:61:12)    at async cls.<computed> [as help] (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/miao-plugin/components/App.js:96:18)
[10:20:28.676][MARK][3889058844:F89A995856DF7B6D51F26F185E671E7F, 3889058844:92D41F38C9D73A1B99D82C1A81406B4C][菜单][喵喵:喵喵帮助(help)][完成3.654秒]
日志如上该如何解决

**Comment by lifnegqaq** [comment]
看网上是puppeteer版本问题，但是降级了还是不行
