### ISSUE TITLE
[Bug]无法连接TypeError: token.split is not a function

### ISSUE THREAD

**Issue by jiangyin14** [TimeRainStarSky/Yunzai-QQBot-Plugin#9]
下面是建立连接时仅有的日志

``` 

[TRSSYz][17:38:09.016][ERRO] [unhandledRejection] TypeError: token.split is not a function
    at QQBotAdapter.connect (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1149:19)
    at file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1222:17
    at new Promise (<anonymous>)
    at QQBotAdapter.load (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1221:13)
    at ListenerLoader.load (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/listener/loader.js:46:23)
    at async Yunzai.run (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/bot.js:97:5) {
  [stack]: [Getter/Setter: 'TypeError: token.split is not a function\n' +
    '    at QQBotAdapter.connect (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1149:19)\n' +
    '    at file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1222:17\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at QQBotAdapter.load (file:///root/TRSS_AllBot/TRSS-Yunzai/plugins/QQBot-Plugin/index.js:1221:13)\n' +
    '    at ListenerLoader.load (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/listener/loader.js:46:23)\n' +
    '    at async Yunzai.run (file:///root/TRSS_AllBot/TRSS-Yunzai/lib/bot.js:97:5)'],
  [message]: 'token.split is not a function'
}

```

**Comment by TimeRainStarSky** [comment]
没按教程安装
